### ISSUE TITLE
Crash when handshaking SSL

### ISSUE THREAD

**Issue by tuanpmt** [emitter-io/emitter#130]
Hi,

Thank you for the great project.

 I was facing the issue when connecting to emitter server using TLS(mbedtls), with this client [espmqtt](https://github.com/tuanpmt/espmqtt). Currently it can work with iot.eclipse.org:8883

Here is the config and server log 
<details>
<summary> EXPLAIN LOG

```
{
	"listen": ":1883",
	"tls": {
		"listen": ":8443",
		"host": "mqtt.****.io",
                "email":"xxxx"
	},
	"cluster": {
		"listen": ":4000",
		"advertise": "public:4000"
	},
	"storage": {
		"provider": "inmemory"
	}
}
```

</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d2c96]

goroutine 86 [running]:
iotcore-mqtt/vendor/github.com/emitter-io/config.(*VaultCache).Get(0x0, 0x9c02c0, 0xc420258360, 0xc420251240, 0xf, 0x97bca0, 0x8d69a0, 0x13d5a19f60801, 0xc4201e7700, 0xc4201e77c0)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/config/provider.go:102 +0x26
iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert.(*Manager).cacheGet(0xc420140180, 0x9c02c0, 0xc420258360, 0xc420251240, 0xf, 0x0, 0x0, 0xc4201e7810)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert/autocert.go:352 +0x86
iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert.(*Manager).cert(0xc420140180, 0x9c02c0, 0xc420258360, 0xc420251240, 0xf, 0x0, 0x0, 0x0)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert/autocert.go:325 +0x339
iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert.(*Manager).GetCertificate(0xc420140180, 0xc4200a49a0, 0x0, 0x0, 0x0)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert/autocert.go:231 +0x326
iotcore-mqtt/vendor/golang.org/x/crypto/acme/autocert.(*Manager).GetCertificate-fm(0xc4200a49a0, 0x410f48, 0xb0, 0x925000)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/config/config.go:113 +0x34
crypto/tls.(*Config).getCertificate(0xc42017b680, 0xc4200a49a0, 0xc420219220, 0x20, 0x20)
	/usr/local/go/src/crypto/tls/common.go:712 +0x326
crypto/tls.(*serverHandshakeState).readClientHello(0xc4202abaf0, 0xc4201e7ae0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_server.go:216 +0x3e1
crypto/tls.(*Conn).serverHandshake(0xc42017f880, 0x97bca0, 0xc42017f9a0)
	/usr/local/go/src/crypto/tls/handshake_server.go:48 +0xae
crypto/tls.(*Conn).Handshake(0xc42017f880, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1331 +0x24e
crypto/tls.(*Conn).Read(0xc42017f880, 0xc420251230, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1139 +0x43
iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener.(*sniffer).Read(0xc4200a4900, 0xc420251230, 0x8, 0x8, 0x8, 0xc420251230, 0x0)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener/listener.go:294 +0x143
io.ReadAtLeast(0x9b8420, 0xc4200a4900, 0xc420251230, 0x8, 0x8, 0x8, 0x88bf00, 0x1, 0xc420251230)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x9b8420, 0xc4200a4900, 0xc420251230, 0x8, 0x8, 0x8, 0x449fa8, 0x13d143f6aee4c)
	/usr/local/go/src/io/io.go:327 +0x58
iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener.(*patriciaTree).matchPrefix(0xc42016cc20, 0x9b8420, 0xc4200a4900, 0x0)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener/matcher.go:88 +0x84
iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener.(*patriciaTree).(iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener.matchPrefix)-fm(0x9b8420, 0xc4200a4900, 0x276f2d083d)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener/matcher.go:48 +0x3e
iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener.(*Listener).serve(0xc4201b2eb0, 0x9c21a0, 0xc42017f880, 0xc420066e40, 0xc420021cc0)
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener/listener.go:177 +0x193
created by iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener.(*Listener).Serve
	/Users/TuanPM/go/src/iotcore-mqtt/vendor/github.com/emitter-io/emitter/network/listener/listener.go:164 +0x15d
```
</details>

**Comment by Kelindar** [comment]
Thanks, we'll have a look, looks like a bug on our end.

**Comment by tuanpmt** [comment]
I'm not sure about this, when i tried to connect to your production server, it is ok for mqtts and wss

```
I (2242) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
D (2252) MQTT_CLIENT: MQTT client_id=ESP32_49C1F4
D (5752) MQTT_CLIENT: Transport connected to mqtts://api.emitter.io:443
I (5752) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
D (6152) MQTT_CLIENT: Connected
I (6152) MQTTS_SAMPLE: MQTT_EVENT_CONNECTED
D (6152) MQTT_CLIENT: mqtt_enqueue id: 0, type=1 successful
D (6162) MQTT_CLIENT: Sent subscribe topic=fxfUhG7FV_GZTDuvR****KGnNUbEAFfB/test/listen/, id: 27473, type=8 successful
I (6172) MQTTS_SAMPLE: sent subscribe successful, msg_id=27473
D (6462) MQTT_CLIENT: msg_type=9, msg_id=27473
D (6462) MQTT_CLIENT: pending_id=27473, pending_msg_count = 1
D (6462) MQTT_CLIENT: Subscribe successful
I (6462) MQTTS_SAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=27473
I (6472) MQTTS_SAMPLE: sent publish successful, msg_id=0
```

**Comment by Kelindar** [comment]
https://github.com/emitter-io/emitter/pull/139

**Comment by Kelindar** [comment]
@tuanpmt It should be fixed now, feel free to reopen this if you are still facing the issue.

**Comment by tuanpmt** [comment]
Thank you @Kelindar 

I have successfully tested it with SSL, And also adding an example for the ESP32 client to use with emitter, it is very useful for IoT applications.

 https://github.com/tuanpmt/espmqtt/tree/master/examples/emitter-client
