### ISSUE TITLE
Access to the path '/sys/class/net/lo/operstate' is denied.

### ISSUE THREAD

**Issue by makyo-dev** [emitter-io/emitter#2]
Hi, I'm trying to install emitter-io on: openSUSE Leap 42.2, Docker version 1.12.6

```sh
$ docker run -d --name emitter -p 127.0.0.1:8888:8080 emitter/server
```

But have an error:

````
Warning: Configuration file 'emitter.conf' does not exist, using default configuration.
Error: No license was found, please provide a valid license key through the configuration file, an EMITTER_LICENSE environment variable or a valid vault key 'secrets/emitter/license'.
Warning: New license: *****
Warning: New secret key: *****
Warning: New license and secret key were generated, please store them in a secure location and restart the server with the license provided.

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/sys/class/net/lo/operstate' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOperationalStatus(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at Emitter.Network.ServiceAddress.FromBinding(IBinding binding)
/deploy.sh: line 2:     7 Aborted                 (core dumped) dotnet Emitter.Server.dll
```

**Comment by Kelindar** [comment]
Seems like some security issue. Could you try running with `–privileged` flag?

**Comment by makyo-dev** [comment]
Thanks! Now it working with
```sh
$ docker run -d --name emitter -p 127.0.0.1:8888:8080 --privileged emitter/server
```

```
Warning: Configuration file 'emitter.conf' does not exist, using default configuration.
Error: No license was found, please provide a valid license key through the configuration file, an EMITTER_LICENSE environment variable or a valid vault key 'secrets/emitter/license'.
Warning: New license: *****
Warning: New secret key: *****
Warning: New license and secret key were generated, please store them in a secure location and restart the server with the license provided.
Listening: 127.0.0.1:8080
Listening: 172.17.0.3:8080
Listening: 127.0.0.1:8443
Listening: 172.17.0.3:8443
Listening: 127.0.0.1:4000
Listening: 172.17.0.3:4000
Warning: Unable to detect TLS/SSL certificate.
Messaging: Starting publisher on thread #15
```
