### ISSUE TITLE
ssl config in kubernetes

### ISSUE THREAD

**Issue by himadrinath** [emitter-io/emitter#267]
@kelindar @Florimond  hi I am using digitalocean Kubernetes I config letsencrypt cert in my loadbalancer but not able to connect using https. can u help me please...……... how can i config my deployment to handle ssl conneection

**Comment by himadrinath** [comment]
@kelindar  here is my broker log

```
2019/09/04 20:40:36 [service] configured logging provider (stderr)
2019/09/04 20:40:36 Replaying from value pointer: {Fid:0 Len:0 Offset:0}
2019/09/04 20:40:36 Iterating file id: 0
2019/09/04 20:40:36 Iteration took: 81.459µs
2019/09/04 20:40:36 [service] configured message storage (ssd)
2019/09/04 20:40:36 [service] configured usage metering (noop)
2019/09/04 20:40:36 [service] configured contracts provider (single)
2019/09/04 20:40:36 [service] configured monitoring sink (self)
2019/09/04 20:40:36 [service] configured node name (ee:ce:6d:94:4a:6c)
2019/09/04 20:40:36 [service] starting the listener (0.0.0.0:8080)
2019/09/04 20:40:36 [tls] setting up certificates with dircache cache
2019/09/04 20:40:36 [service] starting the listener (0.0.0.0:443)
2019/09/04 20:40:36 [service] service started
2019/09/04 20:51:43 [closing] panic recovered: runtime error: slice bounds out of range 
 goroutine 919 [running]:
runtime/debug.Stack(0xc009345d38, 0x100c120, 0x1866f20)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/emitter-io/emitter/internal/broker.(*Conn).Close(0xc0000f5480, 0x3b9aca00, 0x7a4eff)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:297 +0x247
panic(0x100c120, 0x1866f20)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/emitter-io/emitter/internal/network/mqtt.readString(...)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:857
github.com/emitter-io/emitter/internal/network/mqtt.decodeConnect(0xc0002108f4, 0x3, 0x3, 0x3, 0x3)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:640 +0x5fc
github.com/emitter-io/emitter/internal/network/mqtt.DecodePacket(0x12a7600, 0xc000216720, 0x10000, 0x18c0cc0, 0x0, 0x0, 0x18c0cc0)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:211 +0x2d5
github.com/emitter-io/emitter/internal/broker.(*Conn).Process(0xc0000f5480, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:124 +0x19a
created by github.com/emitter-io/emitter/internal/broker.(*Service).onAcceptConn
	/go-build/src/github.com/emitter-io/emitter/internal/broker/service.go:297 +0x6e
```

**Comment by kelindar** [comment]
You need to be able to reach on port 80 from your domain name to the container got letsencrypt to issue a certificate. If you're using a load balancer, redirect port 80 as well and makd sure the domain is setup correctly.

**Comment by himadrinath** [comment]
[domain](http://pubsub.site/keygen) setup correctly and http working but https getting 503 response

**Comment by kelindar** [comment]
There should be 3 ports open: 80 for letsencrypt cert verification, 8080 for HTTP and 443 for HTTPS

**Comment by himadrinath** [comment]
@kelindar  i opened those ports both of them its now working..

do i have to open 3 ports in both of them or just loadbalancer

**Comment by jreyeshdez** [comment]
I have been trying to use SSL in EKS by using a certificate from AWS however I cant reach the broker at 8883 (MQTTS) but I can in 1883. It would be great to see a demo of this if possible. There are no errors in the brokers logs.
- tcp://mqtt.domain.io:1883 --> works
- tcp://mqtt.domain.io:8883 --> does not work

In broker yaml I have ports:
```
ports:
          - containerPort: 8080
          - containerPort: 8883
          - containerPort: 1883
          - containerPort: 4000
          - containerPort: 80
```
and in the load balancer yaml:
```
metadata:
  name: broker-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "certificateArn"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "8883"
...
ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts
    - port: 80
      targetPort: 80
      name: http
```
Am I missing something?
