### ISSUE TITLE
panic recovered: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by montanaflynn** [emitter-io/emitter#329]
Got this panic in a production emitter using `emitter/server:latest` docker image:

```
2020/09/09 01:35:25 [service] configured logging provider (stderr)
badger 2020/09/09 01:35:25 INFO: All 0 tables opened in 0s
badger 2020/09/09 01:35:25 INFO: Replaying file id: 0 at offset: 0
badger 2020/09/09 01:35:25 INFO: Replay took: 2.48µs
badger 2020/09/09 01:35:25 DEBUG: Value log discard stats empty
2020/09/09 01:35:25 [service] configured message storage (ssd)
2020/09/09 01:35:25 [service] configured usage metering (noop)
2020/09/09 01:35:25 [service] configured contracts provider (single)
2020/09/09 01:35:25 [service] configured monitoring sink (self)
2020/09/09 01:35:25 [service] configured node name (ae:b1:cc:f5:0a:d9)
2020/09/09 01:35:25 [service] starting the listener (0.0.0.0:8080)
2020/09/09 01:35:25 [tls] unable to configure certificates, make sure a valid cache or certificate is configured
2020/09/09 01:35:25 [service] service started
2020/09/09 01:35:31 [swarm] peer created (ea:c5:b0:af:45:c1)
2020/09/09 01:35:38 [swarm] peer created (ba:54:8f:83:e8:02)
2020/09/09 01:35:38 [closing] panic recovered: runtime error: invalid memory address or nil pointer dereference
 goroutine 842 [running]:
runtime/debug.Stack(0xc006775a88, 0x119d020, 0x1b2d020)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/emitter-io/emitter/internal/broker.(*Conn).Close(0xc007b22090, 0xbfce2a370001db67, 0x4c72e81)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:353 +0x32d
panic(0x119d020, 0x1b2d020)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/weaveworks/mesh.(*gossipSender).Broadcast(0xc007a8b450, 0xaeb1ccf50ad9, 0x1521c80, 0xc007b1e250)
	/go/pkg/mod/github.com/weaveworks/mesh@v0.0.0-20191105120815-58dbcc3e8e63/gossip.go:202 +0xb2
github.com/weaveworks/mesh.(*gossipChannel).relayBroadcast(0xc0000a3e00, 0xaeb1ccf50ad9, 0x1521c80, 0xc007b1e250)
	/go/pkg/mod/github.com/weaveworks/mesh@v0.0.0-20191105120815-58dbcc3e8e63/gossip_channel.go:116 +0x10b
github.com/weaveworks/mesh.(*gossipChannel).GossipBroadcast(0xc0000a3e00, 0x1521c80, 0xc007b1e250)
	/go/pkg/mod/github.com/weaveworks/mesh@v0.0.0-20191105120815-58dbcc3e8e63/gossip_channel.go:83 +0x4f
github.com/emitter-io/emitter/internal/service/cluster.(*Swarm).Notify(0xc0001757a0, 0x152efc0, 0xc0078d8d80, 0x1)
	/go-build/src/github.com/emitter-io/emitter/internal/service/cluster/swarm.go:359 +0xb5
github.com/emitter-io/emitter/internal/broker.(*Conn).onConnect(0xc007b22090, 0xc0079a8f00, 0x4)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:344 +0x1a6
github.com/emitter-io/emitter/internal/broker.(*Conn).onReceive(0xc007b22090, 0x152f080, 0xc0079a8f00, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:194 +0x7aa
github.com/emitter-io/emitter/internal/broker.(*Conn).Process(0xc007b22090, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:180 +0x1cb
created by github.com/emitter-io/emitter/internal/broker.(*Service).onAcceptConn
	/go-build/src/github.com/emitter-io/emitter/internal/broker/service.go:315 +0x6e
```

**Comment by kelindar** [comment]
@montanaflynn  Do you have a way to reproduce this? Under which circumstances it seems to happen?

**Comment by montanaflynn** [comment]
I have not been able to reproduce it, it happened when scaling up from 0 brokers. 

We're running emitter as a statefulset in kubernetes as described here: https://github.com/emitter-io/emitter/tree/master/deploy/k8s/aws 

We are scaling up from 0 brokers because the emitter brokers are randomly giving these errors after running for awhile:

```
2020/09/09 03:33:42 [conn] error during publish received (the security key provided is not authorized to perform this operation)
```

When restarting them the error goes away without any changes to the clients. 

Restarting the emitter broker statefulset with a "rollout" doesn't work:

`kubectl rollout restart statefulset emitter-broker`

Causes `emitter-broker-2` to restart and it then gets these errors:

```
[pod/emitter-broker-2/emitter-broker] 2020/08/31 17:37:37 [swarm] error during gossip (->[192.168.17.35:4000] error during connection attempt: dial tcp 0.0.0.0:0->192.168.17.35:4000: connect: no route to host)
```

So we've been scaling to 0 and back up which makes them all come online and connect to each other:

```
kubectl scale statefulset emitter-broker --replicas=0
kubectl scale statefulset emitter-broker --replicas=3
```
