### ISSUE TITLE
panic recovered: runtime error: index out of range

### ISSUE THREAD

**Issue by montanaflynn** [emitter-io/emitter#330]
In the middle of our emitter logs we're seeing these panics, I'm not sure what conditions cause it and havn't been able to reproduce it. We're running emitter with 3 brokers on Kubernetes on AWS as described here: https://github.com/emitter-io/emitter/tree/master/deploy/k8s/aws

I've seen these panics:

- `panic recovered: runtime error: index out of range [0] with length 0`
- `panic recovered: runtime error: index out of range [1] with length 1` 
- `panic recovered: runtime error: index out of range [3] with length 3`

Full error logs:

```
2020/09/01 12:01:16 [closing] panic recovered: runtime error: index out of range [0] with length 0
 goroutine 653277 [running]:
runtime/debug.Stack(0xc007002be0, 0x12479e0, 0xc000039780)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/emitter-io/emitter/internal/broker.(*Conn).Close(0xc006dc7320, 0xbfcb699f0149e9b0, 0xc0002f7)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:353 +0x32d
panic(0x12479e0, 0xc000039780)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/emitter-io/emitter/internal/network/mqtt.readUint16(...)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:892
github.com/emitter-io/emitter/internal/network/mqtt.decodeSubscribe(0x1bc98e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:754 +0x33f
github.com/emitter-io/emitter/internal/network/mqtt.DecodePacket(0x1520d80, 0xc006f6a300, 0x10000, 0x1b9e120, 0x0, 0x0, 0x1b9e120)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:226 +0x52c
github.com/emitter-io/emitter/internal/broker.(*Conn).Process(0xc006dc7320, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:174 +0x197
created by github.com/emitter-io/emitter/internal/broker.(*Service).onAcceptConn
	/go-build/src/github.com/emitter-io/emitter/internal/broker/service.go:315 +0x6e

2020/09/01 12:02:08 [closing] panic recovered: runtime error: index out of range [1] with length 1
 goroutine 653815 [running]:
runtime/debug.Stack(0xc007002c10, 0x12479e0, 0xc0079c22c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/emitter-io/emitter/internal/broker.(*Conn).Close(0xc00023b830, 0xbfcb699f014a3722, 0xc0002f7)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:353 +0x32d
panic(0x12479e0, 0xc0079c22c0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/emitter-io/emitter/internal/network/mqtt.readUint16(...)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:893
github.com/emitter-io/emitter/internal/network/mqtt.readString(...)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:882
github.com/emitter-io/emitter/internal/network/mqtt.decodeConnect(0xc007c64344, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:641 +0x842
github.com/emitter-io/emitter/internal/network/mqtt.DecodePacket(0x1520d80, 0xc006e62660, 0x10000, 0x1b9e120, 0x0, 0x0, 0x1b9e120)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:212 +0x2a3
github.com/emitter-io/emitter/internal/broker.(*Conn).Process(0xc00023b830, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:174 +0x197
created by github.com/emitter-io/emitter/internal/broker.(*Service).onAcceptConn
	/go-build/src/github.com/emitter-io/emitter/internal/broker/service.go:315 +0x6e
```

**Comment by montanaflynn** [comment]
This is still happening on a new cluster using the latest docker image `emitter/server:v2.8`:

```
2021/08/06 05:18:17 [conn] error during publish received (the security key provided is not authorized to perform this operation)
2021/08/07 14:10:07 [closing] panic recovered: runtime error: index out of range [0] with length 0
 goroutine 404207 [running]:
runtime/debug.Stack(0xc0069eb468, 0x123fd00, 0xc000037ae0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/emitter-io/emitter/internal/broker.(*Conn).Close(0xc005edc000, 0xc03b4ea201c61663, 0x2d39f7f)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:305 +0x2da
panic(0x123fd00, 0xc000037ae0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/emitter-io/emitter/internal/network/mqtt.readUint16(...)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:892
github.com/emitter-io/emitter/internal/network/mqtt.decodePubrel(...)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:737
github.com/emitter-io/emitter/internal/network/mqtt.DecodePacket(0x1518300, 0xc006293260, 0x10000, 0x1b91ec0, 0x0, 0x0, 0x1b91ec0)
	/go-build/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:222 +0x7c5
github.com/emitter-io/emitter/internal/broker.(*Conn).Process(0xc005edc000, 0x0, 0x0)
	/go-build/src/github.com/emitter-io/emitter/internal/broker/conn.go:129 +0x197
created by github.com/emitter-io/emitter/internal/broker.(*Service).onAcceptConn
	/go-build/src/github.com/emitter-io/emitter/internal/broker/service.go:311 +0x6e

2021/08/07 14:10:26 [conn] error during publish received (the request was invalid or cannot be otherwise served)
```

**Comment by montanaflynn** [comment]
@kelindar the bot closed this with wontfix, not sure if you ever saw it

**Comment by kelindar** [comment]
@montanaflynn I didn't see this indeed. It might happen sometimes, panics are being recovered and if it doesn't happen very often it's very likely that the TCP stack didn't receive a full packet and might have been closed or something. Don't think we need to worry much about this one, but might be worth adding checks to avoid the panic itself.
