### ISSUE TITLE
How to get channel key?

### ISSUE THREAD

**Issue by leenux** [emitter-io/emitter#335]
My work step:

1 download version 2.7 for linux amd64
2 run `./emiter`
3 edit emiter.conf and fill license
4 re-run `./emiter`
5 console is:
```
$ ./emitter 
2020/11/16 14:15:11 [service] configured logging provider (stderr)
2020/11/16 14:15:11 [service] configured message storage (inmemory)
2020/11/16 14:15:11 [service] configured usage metering (noop)
2020/11/16 14:15:11 [service] configured contracts provider (single)
2020/11/16 14:15:11 [service] configured monitoring sink (self)
2020/11/16 14:15:11 [service] configured node name (00:0c:29:dc:50:43)
2020/11/16 14:15:11 [service] starting the listener (0.0.0.0:8080)
2020/11/16 14:15:11 [tls] unable to configure certificates, make sure a valid cache or certificate is configured
2020/11/16 14:15:11 [service] service started
```
6 broswer open url `http://127.0.0.1:8080/keygen`
7 fill `Secret Key` and `Target Channel` and click `Genrate Key` button
8 didnot get channel key and got toast`the security key provided is not authorized to perform this operation`

Try the similar use docker by https://github.com/emitter-io/emitter#get-license and result is same

Quest: How to get the channel key?

**Comment by Florimond** [comment]
My guess is you forgot the final `/`. I should correct the example in the doc indeed...

**Comment by leenux** [comment]
@Florimond Hi,filled `Target Channel` is `demo/`

**Comment by Florimond** [comment]
Well that's odd. I just generated a key for `demo/` with a local emitter running in VS Code, and the license and secret key provided in the document you mention. There must be something obvious happening here... Double check your license and secret key? I don't know what else to do.

If you don't find anything wrong with your license and secret key, maybe you could record a short video/gif beginning at step 2? You can use `ScreenToGif` on windows, or `Peek` on linux.

**Comment by leenux** [comment]
@Florimond Hi,
https://imgur.com/qjW3IWF

**Comment by leenux** [comment]
@Florimond Hi,
```
$ ./emitter 
2020/11/16 17:29:41 [service] unable to find a license, make sure 'license' value is set in the config file or EMITTER_LICENSE environment variable
2020/11/16 17:29:41 [license] generated new license: RfBEIG5zJV4C6bvIAz_VETlkGVVr12MxWTGaSgRbDXyfT0xyGN2F-EHleQT7sDh5m8d1hBISPgQOsz8JEtjQh-sLjsWA3Q0B:2
2020/11/16 17:29:41 [license] generated new secret key: zUCNtJGF-vcpMkOxNQwrS84Jr2Pc7vaD
```

**Comment by Florimond** [comment]
I have just generated a channel key with this licence. As you can see here: 
![image](https://user-images.githubusercontent.com/372102/99249910-1f4fb200-280b-11eb-86c5-da65c3903170.png)

However, if you generated a version 2 license (see the last character in the key), you are not running the latest version of Emitter. We are currently at the version 3 of the license. I can't say for sure this is the issue, but it wouldn't hurt to pull the latest version of Emitter from the repo and test it.

**Comment by leenux** [comment]
I tried to pull docker image latest version(2.8) and generated version 3 key,and toast is same. I will try other way again.

**Comment by Florimond** [comment]
Maybe you have several docker images of Emitter running, and the one that is bound to the port 8080 is not the one you think? Just guessing...

**Comment by leenux** [comment]
I tried again
```
leenux@ubuntu:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
leenux@ubuntu:~$ docker run --name emitter -p 8080:8080 --restart=unless-stopped emitter/server
2020/11/16 12:35:02 [service] unable to find a license, make sure 'license' value is set in the config file or EMITTER_LICENSE environment variable
2020/11/16 12:35:02 [license] generated new license: PfA8IGNQ-7Jmx2iqfI5wuAy333RynzlInltAb02KhwdPN5yHEFl3rWBpYUJ2qa1pWb6jQJulus_eAYTh8tgJAQ:3
2020/11/16 12:35:02 [license] generated new secret key: Aa4PxhIY41ORZ3n2zJt3W2bhJp1CBImZ
leenux@ubuntu:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS                                        NAMES
b56e31997aee        emitter/server      "./emitter"         22 seconds ago      Up Less than a second   4000/tcp, 8443/tcp, 0.0.0.0:8080->8080/tcp   emitter
leenux@ubuntu:~$ docker stop b56e31997aee
b56e31997aee
leenux@ubuntu:~$ docker rm b56e31997aee
b56e31997aee
leenux@ubuntu:~$ docker run --name emitter -p 8080:8080 -e EMITTER_LICENSE=PfA8IGNQ-7Jmx2iqfI5wuAy333RynzlInltAb02KhwdPN5yHEFl3rWBpYUJ2qa1pWb6jQJulus_eAYTh8tgJAQ --restart=unless-stopped emitter/server
2020/11/16 12:35:46 [service] configured logging provider (stderr)
2020/11/16 12:35:46 [service] configured message storage (inmemory)
2020/11/16 12:35:46 [service] configured usage metering (noop)
2020/11/16 12:35:46 [service] configured contracts provider (single)
2020/11/16 12:35:46 [service] configured monitoring sink (self)
2020/11/16 12:35:53 [service] configured node name (02:42:ac:11:00:02)
2020/11/16 12:35:53 [service] starting the listener (0.0.0.0:8080)
2020/11/16 12:35:53 [tls] unable to configure certificates, make sure a valid cache or certificate is configured
2020/11/16 12:35:53 [service] service started

```
[https://github.com/leenux/mygraphbed/blob/master/123.png](https://github.com/leenux/mygraphbed/blob/master/123.png)

**Comment by leenux** [comment]
My other try on Windows 10 and found error msg:
```
> .\emitter
2020/11/16 20:21:26 [service] configured logging provider (stderr)
2020/11/16 20:21:26 [service] configured message storage (inmemory)
2020/11/16 20:21:26 [service] configured usage metering (noop)
2020/11/16 20:21:26 [service] configured contracts provider (single)
2020/11/16 20:21:26 [service] configured monitoring sink (self)
2020/11/16 20:21:26 [service] configured node name (dc:71:96:81:9b:24)
2020/11/16 20:21:26 [service] starting the listener (0.0.0.0:8080)
2020/11/16 20:21:26 [tls] unable to configure certificates, make sure a valid cache or certificate is configured
2020/11/16 20:21:26 [service] service started
2020/11/16 20:24:33 [closing] panic recovered: runtime error: slice bounds out of range
 goroutine 103 [running]:
runtime/debug.Stack(0xc000525d38, 0xcdf860, 0x1611250)
        C:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/emitter-io/emitter/internal/broker.(*Conn).Close(0xc000260200, 0xc00003b200, 0x4)
        C:/gopath/src/github.com/emitter-io/emitter/internal/broker/conn.go:301 +0x24e
panic(0xcdf860, 0x1611250)
        C:/go/src/runtime/panic.go:522 +0x1c3
github.com/emitter-io/emitter/internal/network/mqtt.readString(...)
        C:/gopath/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:857
github.com/emitter-io/emitter/internal/network/mqtt.decodeConnect(0xc00052803c, 0x3, 0x3, 0x3, 0x3)
        C:/gopath/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:640 +0x603
github.com/emitter-io/emitter/internal/network/mqtt.DecodePacket(0x1003fe0, 0xc0001da120, 0x10000, 0x16261c0, 0x0, 0x0, 0x16261c0)
        C:/gopath/src/github.com/emitter-io/emitter/internal/network/mqtt/mqtt.go:211 +0x2dc
github.com/emitter-io/emitter/internal/broker.(*Conn).Process(0xc000260200, 0x0, 0x0)
        C:/gopath/src/github.com/emitter-io/emitter/internal/broker/conn.go:128 +0x1a7
created by github.com/emitter-io/emitter/internal/broker.(*Service).onAcceptConn
        C:/gopath/src/github.com/emitter-io/emitter/internal/broker/service.go:303 +0x75
```

**Comment by leenux** [comment]
@Florimond Can you view your emitter.conf file? and I can compare.
Below is my emitter.conf
```
{
	"listen": ":8080",
	"license": "RfBEIG5zJV4C6bvIAz_VETlkGVVr12MxWTGaSgRbDXyfT0xyGN2F-EHleQT7sDh5m8d1hBISPgQOsz8JEtjQh-sLjsWA3Q0B",
	"limit": {},
	"tls": {
		"listen": ":443",
		"host": ""
	},
	"cluster": {
		"listen": ":4000",
		"advertise": "external:4000"
	},
	"storage": {
		"provider": "inmemory"
	}
}
```

**Comment by leenux** [comment]
I compiled v2.8 and insert a few log for trace.
```
func (p *Provider) CreateKey(rawMasterKey, channel string, access uint8, expires time.Time) (string, *errors.Error) {
	log.Printf("CreateKey rawMasterKey=%s\n", rawMasterKey)
	masterKey, err := p.DecryptKey(rawMasterKey)
	log.Printf("CreateKey-pin-1\n")
	//if err != nil || !masterKey.IsMaster() || masterKey.IsExpired() {
	if err != nil {
		log.Printf("CreateKey-DecryptKey return err %s\n", err.Error())
		return "", errors.ErrUnauthorized
	}
	if masterKey != nil {
		if !masterKey.IsMaster() {
			log.Printf("CreateKey masterKey is not masterkey\n")
			return "", errors.ErrUnauthorized
		}
		if masterKey.IsExpired() {
			log.Printf("CreateKey masterKey is expired\n")
			return "", errors.ErrUnauthorized
		}
	}
	log.Printf("CreateKey-pin-2\n")
```
Result is https://imgur.com/DOv41Xn

**Comment by leenux** [comment]
Already solved.
`"license": "RfBEIG5zJV4C6bvIAz_VETlkGVVr12MxWTGaSgRbDXyfT0xyGN2F-EHleQT7sDh5m8d1hBISPgQOsz8JEtjQh-sLjsWA3Q0B"` MUST add version
`"license": "RfBEIG5zJV4C6bvIAz_VETlkGVVr12MxWTGaSgRbDXyfT0xyGN2F-EHleQT7sDh5m8d1hBISPgQOsz8JEtjQh-sLjsWA3Q0B:3"`
Its work fine

**Comment by Florimond** [comment]
Hey @leenux ,

sorry I didn't see your message asking for my config file. But I'm glad the issue is solved!
