### ISSUE TITLE
IPv6 issues

### ISSUE THREAD

**Issue by gmlewis** [emitter-io/emitter#369]
Emitter has been running locally on my Linux Mint Cinnamon 19.3 box for months now, and suddenly it refuses to start up.
The only thing I can think of is that Linux possibly flipped some switch from `IPv4` to `IPv6`.
Here is the error:

```bash
$ cat emitter.conf 
{
	"listen": ":8081",
	"license": "OQ...wE:3",
	"limit": {},
	"tls": {
		"listen": ":443",
		"host": ""
	},
	"cluster": {
		"listen": ":4000",
		"advertise": "external:4000"
	},
	"storage": {
		"provider": "inmemory"
	}
}
$ emitter
2021/06/17 13:28:36 [service] configured logging provider (stderr)
2021/06/17 13:28:36 [service] configured message storage (inmemory)
2021/06/17 13:28:36 [service] configured usage metering (noop)
2021/06/17 13:28:36 [service] configured contracts provider (single)
2021/06/17 13:28:36 [service] configured monitoring sink (self)
panic: address 2603:9001:8d01:f500:c1ac:df41:1cbe:8cbc:4000: too many colons in address [recovered]
	panic: address 2603:9001:8d01:f500:c1ac:df41:1cbe:8cbc:4000: too many colons in address

goroutine 1 [running]:
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0003765a0, 0x118f480, 0xc0001367c0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:39 +0xd4
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc000376600, 0x118f480, 0xc0001367c0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow.cli/internal/flow.(*Step).callDo.func1(0xc000376630, 0x0, 0x0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:52 +0x4e
panic(0x118f480, 0xc0001367c0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/emitter-io/emitter/internal/service/cluster.NewSwarm(0xc00012b8c0, 0x12858c6)
	/home/glenn/go/src/github.com/emitter-io/emitter/internal/service/cluster/swarm.go:82 +0x7a5
github.com/emitter-io/emitter/internal/broker.NewService(0x13ff7c0, 0xc00030da40, 0xc00024d130, 0x2, 0x2, 0xc00024d130)
	/home/glenn/go/src/github.com/emitter-io/emitter/internal/broker/service.go:142 +0x21fa
main.listen(0xc0003153b0, 0xc0003153c0)
	/home/glenn/go/src/github.com/emitter-io/emitter/main.go:64 +0x2ac
main.main.func1()
	/home/glenn/go/src/github.com/emitter-io/emitter/main.go:38 +0x33
github.com/jawher/mow.cli/internal/flow.(*Step).callDo(0xc000376630, 0x0, 0x0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:55 +0x70
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc000376630, 0x0, 0x0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:25 +0x45
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0003765d0, 0x0, 0x0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc00018fe98, 0x0, 0x0)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow%2ecli.(*Cmd).parse(0xc000173300, 0xc0001181a0, 0x0, 0x0, 0xc00018fe98, 0xc00018fe98, 0xc0003765a0, 0x30, 0x120c640)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/commands.go:681 +0x545
github.com/jawher/mow%2ecli.(*Cli).parse(0xc0003153b0, 0xc0001181a0, 0x0, 0x0, 0xc00018fe98, 0xc00018fe98, 0xc0003765a0, 0x3, 0xc00037ee40)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/cli.go:76 +0x85
github.com/jawher/mow%2ecli.(*Cli).Run(0xc0003153b0, 0xc0001181a0, 0x1, 0x1, 0x25, 0x12befb8)
	/home/glenn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/cli.go:105 +0x129
main.main()
	/home/glenn/go/src/github.com/emitter-io/emitter/main.go:48 +0x318
```

**Comment by kelindar** [comment]
@gmlewis upgraded and merged your fix: https://github.com/emitter-io/emitter/pull/370

**Comment by gmlewis** [comment]
Thank you, @kelindar !
Emitter is now working for me again locally.
Closing issue.
